export const TUNING = {
  animation: {
    direction: "down",
    rollBy: "character",
    stagger: 45,
    duration: 300,
    exitOffset: 50,
    easing: "cubic-bezier(0.34, 1.56, 0.64, 1)",
    bounce: 0.6,
    colorFade: 280,
    skipUnchanged: true,
    interrupt: true,
  },
  variation: {
    indexFrequency: 12.9898,
    channelFrequency: 78.233,
    seedScale: 43758.5453,
    durationChannel: 1,
    staggerChannel: 2,
    tiltChannel: 3,
  },
  glyph: {
    tailDurationMultiplier: 0.75,
    durationVariationStrength: 0.45,
    tailStaggerStartMultiplier: 0.5,
    tailStaggerStepMultiplier: 0.25,
    staggerVariationStrength: 0.25,
    maximumTiltDegrees: 5,
    tiltDecimalPlaces: 2,
  },
  width: {
    tailCollapseDelayMultiplier: 0.55,
    tailCollapseDurationMultiplier: 0.6,
    newSlotExpansionDurationMultiplier: 0.45,
    minimumTransitionMs: 140,
    resizeEasing: "cubic-bezier(0.2, 0, 0, 1)",
    minimumVisibleChangePx: 0.5,
  },
  layout: {
    probeOffscreenPositionPx: -9999,
    fallbackLineHeightMultiplier: 1.3,
    fallbackCharacterHeightPx: 18,
    characterTransformOrigin: "50% 50%",
    characterRestTransform: "translateY(0) rotate(0deg)",
  },
  chromatic: {
    hueStartDegrees: 0,
    hueSpreadDegrees: 320,
    saturationPercent: 92,
    lightnessPercent: 60,
    fullHueRotationDegrees: 360,
  },
  lifecycle: {
    completionBufferMs: 80,
    flashRevertDelayMs: 1400,
  },
} as const;
